apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ .Values.grafanaName }}-loki
spec:
  instanceSelector:
    matchLabels:
      name: {{ .Values.grafanaName }}
  title: Loki Dashboards
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ .Values.grafanaName }}-k8s
spec:
  instanceSelector:
    matchLabels:
      name: {{ .Values.grafanaName }}
  title: k8s Dashboards