{{ $global := . }}
{{- $kind := default "Deployment" $global.Values.global.deploymentKind }}
{{- range $serviceName, $serviceValues := .Values.services }}
{{- $globalValuesDict := $global.Values.global | toYaml -}}
{{- $values := fromYaml $globalValuesDict -}}
{{- $values = set $values "name" $serviceName -}}
{{- $values := mergeOverwrite $values $serviceValues -}}
{{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $service }}
---
{{- if eq $kind "Rollout" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-preview
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    {{- $rolloutAnnotations := default dict (get (default dict $.Values.rolloutAnalysis.strategy.bluegreen.prePromotionAnalysis.analysisRunMetadata) "annotations") }}
    {{- toYaml (mergeOverwrite
                (dict)
                (fromYaml (include "stack.annotations" $service ))
                (default dict $rolloutAnnotations) 
                (dict "argocd.argoproj.io/sync-options" "ServerSideApply=false")
    ) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
