baseDomain: "example.dev.czi.team"

gatewayName: "envoy-gateway"
gatewayNamespace: "envoy-gateway"

proxyNamespace: "envoy-gateway-controller"

externalHostnamePrefix: "access-gw"
internalHostnamePrefix: "access-gw-internal"

proxyProtocolV2: true

deletionProtection: true

internal:
  enabled: false

additionalInternalNLBs: []

tags: {}
