apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ..

helmCharts:
- name: basic
  releaseName: basic
  namespace: happy
  version: 0.1.0
  valuesFile: values.yaml