{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restarter-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restarter-binding
subjects:
- kind: ServiceAccount
  name: restarter
roleRef:
  kind: Role
  name: restarter-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}