{{- if .Values.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restarter
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | default .Chart.Version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/version: {{ .Chart.AppVersion | default .Chart.Version | quote }}
            app.kubernetes.io/managed-by: {{ .Release.Service }}
            app.kubernetes.io/component: restarter-job
        spec:
          serviceAccountName: restarter
          containers:
          - name: restarter
            image: {{ .Values.runner.image | quote }}
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment/{{ .Values.target.deployment }} -n {{ .Values.target.namespace }}
          restartPolicy: OnFailure
{{- end }}