{{- if ne .Values.global.rollout.analysisTemplate.enabled false}}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ default (printf "%s-%s-analysis" .Release.Name .Chart.Name) .Values.global.rollout.analysisTemplate.name }}
  labels:
    {{- include "stack.labels" . | nindent 4 }}
spec:
  args:
    {{- range .Values.global.rollout.analysisTemplate.args | default list }}
    - name: {{ .name }}
    {{- end }}
    - name: target-service-name
    - name: target-service-namespace
  metrics:
  {{- range .Values.global.rollout.analysisTemplate.metrics }}
  - name: {{ .name }}
    {{- if .interval }}
    interval: {{ .interval }}
    {{- end }}
    {{- if .count }}
    count: {{ .count }}
    {{- end }}
    {{- if .initialDelay }}
    initialDelay: {{ .initialDelay }}
    {{- end }}
    {{- if .timeout }}
    timeout: {{ .timeout }}
    {{- end }}
    {{- if .successCondition }}
    successCondition: {{ .successCondition | quote }}
    {{- end }}
    {{- if .failureCondition }}
    failureCondition: {{ .failureCondition | quote }}
    {{- end }}
    provider:
      {{- toYaml .provider | nindent 8 }}
  {{- end }}
  {{ if ne .Values.global.rollout.analysisTemplate.enableDefaultMetrics false }}
  - name: http-success-rate
    interval: "10s"
    count: 1
    successCondition: "result[0] >= 0.99"
    failureCondition: "result[0] < 0.9"
    provider:
      prometheus:
        address: http://loki-stack-prometheus-server.loki.svc.cluster.local:80
        query: |
          sum(rate(nginx_ingress_controller_requests{status=~"2..|3..", service="{{ `{{ args.target-service-name }}` }}"}[5m]))/sum(rate(nginx_ingress_controller_requests{service="{{ `{{ args.target-service-name }}` }}"}[5m]))
  - name: http-latency
    interval: "1m"
    count: 1
    successCondition: "result[0] < 0.5"
    failureCondition: "result[0] > 1.0"
    provider:
      prometheus:
        address: http://loki-stack-prometheus-server.loki.svc.cluster.local:80
        query: |
           histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status=~"2..|3..", service="{{ `{{ args.target-service-name }}` }}"}[5m])) by (le))
  - name: cpu-utilization
    interval: "1m"
    count: 1
    successCondition: "result[0] < 0.8"
    failureCondition: "result[0] > 0.9"
    provider:
      prometheus:
        address: http://loki-stack-prometheus-server.loki.svc.cluster.local:80
        query: |
          {{ $targetPodRegex := printf "{{ args.target-service-name }}-.*" }}
          sum(rate(container_cpu_usage_seconds_total{namespace="{{`{{ args.target-service-namespace }}`}}", pod=~"{{ $targetPodRegex }}"}[5m])) / sum(kube_pod_container_resource_limits{resource="cpu", unit="core", namespace="{{`{{ args.target-service-namespace }}` }}", pod=~"{{ $targetPodRegex }}"})
  {{- end }}
{{- end }}