{{- if default false .Values.global.rollout.analysisTemplate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ default (printf "%s-%s-analysis" .Release.Name .Chart.Name) .Values.global.rollout.analysisTemplate.name }}
  labels:
    {{- include "stack.labels" . | nindent 4 }}
spec:
  args:
    {{- range .Values.global.rollout.analysisTemplate.args | default list }}
    - name: {{ .name }}
    {{- end }}
    - name: target-service-name
  metrics:
  {{- range .Values.global.rollout.analysisTemplate.metrics }}
  - name: {{ .name }}
    {{- if .interval }}
    interval: {{ .interval }}
    {{- end }}
    {{- if .count }}
    count: {{ .count }}
    {{- end }}
    {{- if .initialDelay }}
    initialDelay: {{ .initialDelay }}
    {{- end }}
    {{- if .timeout }}
    timeout: {{ .timeout }}
    {{- end }}
    {{- if .successCondition }}
    successCondition: {{ .successCondition | quote }}
    {{- end }}
    {{- if .failureCondition }}
    failureCondition: {{ .failureCondition | quote }}
    {{- end }}
    provider:
      {{- toYaml .provider | nindent 8 }}
  {{- end }}
  - name: http-success-rate
    interval: "10s"
    count: 1
    successCondition: "result.data.result[0].value[1] > 0.99"
    failureCondition: "result.data.result[0].value[1] < 0.90"
    provider:
      prometheus:
        address: http://loki-stack-prometheus-server.loki.svc.cluster.local:80
        query: |
          sum(rate(nginx_ingress_controller_requests{status=~"2..", service="{{ `{{ args.target-service-name }}` }}"}[5m]))
          /
          sum(rate(nginx_ingress_controller_requests{service="{{ `{{ args.target-service-name }}` }}"}[5m]))
{{- end }} 