apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: envoy-requestid-extension
spec:
  services:
    - name:  {{ include "stack.fullname" . }}
  resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: test-listener