{{ $global := . }}
{{ range $cronJobName, $cronJobValues := .Values.cronJobs }}
  {{- if $cronJobValues.enable | default true }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $cronJobName -}}
  {{- $values := mergeOverwrite $values $cronJobValues -}}
  {{- $cronJob := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $cronJob -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "service.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  {{- if .Values.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "service.serviceAccountName" . }}
          containers:
          - name: {{ include "service.fullname" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if and .Values.args (ne (len .Values.args) 0) }}
            args:
              {{- toYaml .Values.args | nindent 14 }}
            {{- end }}
            {{- if and .Values.command (ne (len .Values.command) 0) }}
            command:
              {{- toYaml .Values.command | nindent 14 }}
            {{- end }}
            livenessProbe:
              {{- include "container.probe" .Values.livenessProbe | nindent 14 }}
            readinessProbe:
              {{- include "container.probe" .Values.readinessProbe | nindent 14 }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            {{- include "service.configuration" . | nindent 12 }}
            {{- include "service.nonsensitiveEnvVars" (list $global.Values.global $cronJob.Values) | nindent 12 }}
          {{- range $i, $container := .Values.sidecars }}
          {{- $imageDict := fromYaml (include "image" $container) }}
          {{- $container = mergeOverwrite $container $imageDict }}
          {{- with omit $container "envFrom" "env" }}
          - {{- toYaml . | nindent 12 }}
            {{- include "service.configuration" $cronJob | nindent 12}}
          {{- end }}
          {{- include "service.nonsensitiveEnvVars" (list $global.Values.global $cronJob.Values $container) | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
{{ if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with mergeOverwrite 
            (dict)
            .Values.annotations
            .Values.serviceAccount.annotations
  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}