{{ $global := . }}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $service -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    {{- include "stack.annotations" $service | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and (ne (trim .Values.appConfig.envSecretName) "") (ne (trim .Values.appConfig.envSecretName) "") }}
          envFrom:
            {{- if ne (trim .Values.appConfig.envSecretName) "" }}
            - secretRef:
                name: {{ .Values.appConfig.envSecretName }}
            {{- end }}
            {{- if ne (trim .Values.appConfig.stackSecretName) "" }}
            - secretRef:
                name: {{ .Values.appConfig.stackSecretName }}
            {{- end }}
          {{- end }}
        {{- range $i, $container := .Values.sidecars }}
        {{- with omit $container "envFrom" }}
        - {{- toYaml . | nindent 10 }}
          {{- if and (ne (trim $service.Values.appConfig.envSecretName) "") (ne (trim $service.Values.appConfig.envSecretName) "") }}
          envFrom:
            {{- if ne (trim $service.Values.appConfig.envSecretName) "" }}
            - secretRef:
                name: {{ $service.Values.appConfig.envSecretName }}
            {{- end }}
            {{- if ne (trim $service.Values.appConfig.stackSecretName) "" }}
            - secretRef:
                name: {{ $service.Values.appConfig.stackSecretName }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
      initContainers:
      {{- range $i, $container := .Values.initContainers }}
      {{- with omit $container "envFrom" }}
        - {{- toYaml . | nindent 10 }}
          {{- if and (ne (trim $service.Values.appConfig.envSecretName) "") (ne (trim $service.Values.appConfig.envSecretName) "") }}
          envFrom:
            {{- if ne (trim $service.Values.appConfig.envSecretName) "" }}
            - secretRef:
                name: {{ $service.Values.appConfig.envSecretName }}
            {{- end }}
            {{- if ne (trim $service.Values.appConfig.stackSecretName) "" }}
            - secretRef:
                name: {{ $service.Values.appConfig.stackSecretName }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}