{{ $global := . }}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}

{{- with $service -}}
{{ range $secretsKey, $secretValue := .Values.appSecrets }}
--- 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretValue.secretName }}
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: "10m"
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - target: Data
          literal: "{{ {{ range $key, $value := . }}{{ range $name, $val := $value | fromJson }}{{$name | upper}}: {{$val}}{{ end }}{{ end }} }}"
  data:
    - secretKey: {{ $secretValue.secretName }}
      remoteRef:
        key: {{ $secretValue.secretKey }}
{{end}}
{{end}}
{{end}}
