{{- $global := . -}}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $service }}

{{- if .Values.gateway.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- $mergedAnnotations := mergeOverwrite (dict) (.Values.annotations) (.Values.gateway.annotations) }}
  {{- if $mergedAnnotations }}
  annotations:
    {{- toYaml $mergedAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.parentRefs }}
  parentRefs:
    {{- range .Values.gateway.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.gateway.hostnames }}
  hostnames:
    {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.rules }}
    - matches:
        - path:
            type: {{ .pathType | default "PathPrefix" }}
            value: {{ .path | default "/" }}
          {{- if .headers }}
          headers:
            {{- range .headers }}
            - name: {{ .name }}
              value: {{ .value }}
              {{- if .type }}
              type: {{ .type }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .queryParams }}
          queryParams:
            {{- range .queryParams }}
            - name: {{ .name }}
              value: {{ .value }}
              {{- if .type }}
              type: {{ .type }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .method }}
          method: {{ .method }}
          {{- end }}
      backendRefs:
        - name: {{ include "service.fullname" $service }}
          port: {{ $service.Values.service.port | int }}
      {{- if $service.Values.gateway.filters }}
      filters:
        {{- toYaml $service.Values.gateway.filters | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
