{{ $global := . }}
{{- $allHosts := list -}}
{{- $allOIDCProtectedServces := list -}}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}

  {{- with $values -}}
  {{ $serviceScope := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" .}}
  {{- if and .ingress.oidcProtected .ingress.enabled -}}
    {{ range $i, $path := .ingress.paths }}
      {{- if (eq $path.pathType "Exact") -}}
      {{- $allOIDCProtectedServces = append 
        $allOIDCProtectedServces 
        (printf "http://%s.%s.svc.cluster.local:%d%s" 
          (include "service.fullname" $serviceScope) 
          $global.Release.Namespace 
          ($values.service.port | int) 
          ($path.path)) 
      -}}
      {{- else -}}
      {{- $allOIDCProtectedServces = append 
        $allOIDCProtectedServces 
        (printf "http://%s.%s.svc.cluster.local:%d%s" 
          (include "service.fullname" $serviceScope) 
          $global.Release.Namespace 
          ($values.service.port | int)
          (printf "%s/" $path.path | replace "//" "/"))
      -}}
      {{- end -}}
    {{- end -}}

  {{ range $i, $rule := .ingress.rules }}
  {{- $allHosts = append $allHosts $rule.host }}
  {{- end -}}

  {{- end -}}
  {{- end -}}
{{- end -}}

{{ $globalValues := .Values.global }}
{{ $scope := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $globalValues}}
{{ with $scope }}
{{- if .Values.oidcProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidcProxy.name" . }}
  labels:
    {{- include "oidcProxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.oidcProxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "oidcProxy.selectorLabels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with (mergeOverwrite 
                    (dict)
                    (.Values.annotations)
                    (.Values.podAnnotations)  
                    (.Values.oidcProxy.annotations)
        ) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "oidcProxy.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - --session-store-type=redis
            - --http-address=0.0.0.0:{{ include "oidcProxy.port" . }}
            - --provider=oidc
            - --email-domain=*
            - --cookie-secure=true
            - --set-xauthrequest
            - --cookie-domain={{- include "baseDomain" . }}
            - --whitelist-domain=.{{- include "baseDomain" . }}
            - --skip-provider-button=true
            - --pass-authorization-header=true
            - --reverse-proxy
            - --skip-jwt-bearer-tokens
            - --cookie-refresh={{ .Values.oidcProxy.cookieRefresh }}

            {{- range $allOIDCProtectedServces }}
            - --upstream={{ . }}
            {{- end -}}

            {{- range .Values.oidcProxy.skipAuth }}
            {{ if contains "*" .method }}
            # for backwards compatibility, could also just be provided using extraArgs
            - --skip-auth-route={{ .path }}
            {{- else -}}
            - --skip-auth-route={{ .method }}={{ .path }}
            {{- end -}}
            {{- end -}}

            {{ $cookiePrefix := list }}
            {{ range .Values.oidcProxy.extraArgs }}
            {{ if (hasPrefix "--cookie-domain" . ) }}
              {{ $cookiePrefix = append $cookiePrefix . }}
            {{ end }}
            {{ end }} 
            {{- range $allHosts -}}
            {{- printf "- --whitelist-domain=%s" . | nindent 12 -}}

            {{ if eq (len $cookiePrefix) 0 }}
            # if a user provides a cookie-domain flag, we want to use that instead of the 
            # default cookie-domain
            {{- printf "- --cookie-domain=%s" . | nindent 12 -}}
            {{ end }}
            
            {{- end -}}
            {{- if gt (len .Values.oidcProxy.extraArgs) 0 }}
            {{- toYaml .Values.oidcProxy.extraArgs | nindent 12}}
            {{- end }}
          {{- include "image" .Values.oidcProxy  | nindent 10 }}
          {{- if gt (len (fromYamlArray (include "oidcProxy.envFrom" .))) 0 }}
          {{- include "oidcProxy.envFrom" . | nindent 10 }}
          {{- else }}
          envFrom: []
          {{- end }}
          imagePullPolicy: IfNotPresent
          name:  {{ include "oidcProxy.name" . }}
          ports:
            - containerPort: {{ include "oidcProxy.port" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.oidcProxy.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.oidcProxy.volumeMounts| nindent 12 }}
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "oidcProxy.selectorLabels" . | nindent 16 }}      
      volumes:
        {{- toYaml .Values.volumes | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- with (mergeOverwrite 
              (dict)
              (.Values.annotations)
              (.Values.oidcProxy.annotations)
        ) }}
        {{- toYaml . | nindent 4 }}
        {{- end }}
  labels:
    {{- include "oidcProxy.labels" . | nindent 4 }}
  name: {{ include "oidcProxy.name" . }}
spec:
  ports:
    - name: http
      port: {{ include "oidcProxy.port" . }}
      protocol: TCP
      targetPort: {{ include "oidcProxy.port" . }}
  selector:
    {{- include "oidcProxy.selectorLabels" . | nindent 4 }}

---

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oidcProxy.name" . }}
  {{- $certManagerAnnotations := (fromYaml (include "certManagerAnnotations" . )) }}
  annotations:
  {{- with (mergeOverwrite 
              (dict)
              ($certManagerAnnotations)
              (.Values.annotations)
              (.Values.oidcProxy.annotations)
      ) -}}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "oidcProxy.authDomain" . }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: {{ include "oidcProxy.name" . }}
                port:
                  number: {{ include "oidcProxy.port" . }}
    {{- $scope := . }}
    {{- range $i, $host := $allHosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: {{ include "oidcProxy.name" $scope }}
                port:
                  number: {{ include "oidcProxy.port" $scope }}
    {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
