{{ $global := . }}
{{ $globalValues := .Values.global }}
{{ $scope := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $globalValues}}
{{ with $scope }}
{{- if .Values.oidcProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidcProxy.name" . }}
  labels:
    {{- include "oidcProxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.oidcProxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "oidcProxy.selectorLabels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        {{- include "oidcProxy.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - --session-store-type=redis
            - --http-address=0.0.0.0:{{ include "oidcProxy.port" . }}
            - --provider=oidc
            - --email-domain=*
            - --cookie-secure=true
            - --set-authorization-header
            - --set-xauthrequest
            - --cookie-domain={{- include "baseDomain" . }}
            - --whitelist-domain=.{{- include "baseDomain" . }}
            - --skip-provider-button=true
            - --pass-authorization-header=true
            - --reverse-proxy
            {{- if gt (len .Values.oidcProxy.extraArgs) 0 }}
            {{- toYaml .Values.oidcProxy.extraArgs | nindent 12}}
            {{- end }}
          {{- include "image" .Values.oidcProxy  | nindent 10 }}
          {{- if gt (len (fromYamlArray (include "oidcProxy.envFrom" .))) 0 }}
          {{- include "oidcProxy.envFrom" . | nindent 10 }}
          {{- else }}
          envFrom: [] # empty
          {{- end }}
          imagePullPolicy: IfNotPresent
          name:  {{ include "oidcProxy.name" . }}
          ports:
            - containerPort: {{ include "oidcProxy.port" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.oidcProxy.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "oidcProxy.labels" . | nindent 4 }}
  name: {{ include "oidcProxy.name" . }}
spec:
  ports:
    - name: http
      port: {{ include "oidcProxy.port" . }}
      protocol: TCP
      targetPort: {{ include "oidcProxy.port" . }}
  selector:
    {{- include "oidcProxy.selectorLabels" . | nindent 4 }}

---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oidcProxy.name" . }}
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "oidcProxy.authDomain" . }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: {{ include "oidcProxy.name" . }}
                port:
                  number: {{ include "oidcProxy.port" . }}
{{- end -}}
{{- end -}}
{{- end -}}