{{ $global := . }}
{{- $allHosts := list -}}
{{- $allOIDCProtectedServces := list -}}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}

  {{- with $values -}}
  {{- if .ingress.oidcProtected -}}

  {{- $allOIDCProtectedServces = append 
    $allOIDCProtectedServces 
    (printf "http://%s.%s.svc.cluster.local:%d" $serviceName $global.Release.Namespace ($values.service.port | int)) 
  -}}

  {{ range $i, $rule := .ingress.rules }}
  {{- $allHosts = append $allHosts $rule.host }}
  {{- end -}}

  {{- end -}}
  {{- end -}}
{{- end -}}

{{ $globalValues := .Values.global }}
{{ $scope := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $globalValues}}
{{ with $scope }}
{{- if .Values.oidcProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidcProxy.name" . }}
  labels:
    {{- include "oidcProxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.oidcProxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "oidcProxy.selectorLabels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with (mergeOverwrite 
                    (dict)
                    (.Values.annotations)
                    (.Values.podAnnotations)  
                    (.Values.oidcProxy.annotations)
        ) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "oidcProxy.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - --session-store-type=redis
            - --http-address=0.0.0.0:{{ include "oidcProxy.port" . }}
            - --provider=oidc
            - --email-domain=*
            - --cookie-secure=true
            - --set-authorization-header
            - --set-xauthrequest
            - --cookie-domain={{- include "baseDomain" . }}
            - --whitelist-domain=.{{- include "baseDomain" . }}
            - --skip-provider-button=true
            - --pass-authorization-header=true
            - --reverse-proxy
            - --skip-jwt-bearer-tokens

            {{- range $allOIDCProtectedServces }}
            - --upstream={{ . }}
            {{ end -}}

            {{- range .Values.oidcProxy.skipAuth }}
            # for backwards compatibility, could also just be provided using extraArgs
            {{ if contains "*" .method }}
            - --skip-auth-route={{ .path }}
            {{- else -}}
            - --skip-auth-route={{ .method }}={{ .path }}
            {{- end -}}
            {{- end -}}

            {{- range $allHosts -}}
            {{- printf "- --whitelist-domain=%s" . | nindent 12 -}}
            {{- printf "- --cookie-domain=%s" . | nindent 12 -}}
            {{- end -}}
            {{- if gt (len .Values.oidcProxy.extraArgs) 0 }}
            {{- toYaml .Values.oidcProxy.extraArgs | nindent 12}}
            {{- end }}
          {{- include "image" .Values.oidcProxy  | nindent 10 }}
          {{- if gt (len (fromYamlArray (include "oidcProxy.envFrom" .))) 0 }}
          {{- include "oidcProxy.envFrom" . | nindent 10 }}
          {{- else }}
          envFrom: []
          {{- end }}
          imagePullPolicy: IfNotPresent
          name:  {{ include "oidcProxy.name" . }}
          ports:
            - containerPort: {{ include "oidcProxy.port" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.oidcProxy.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.oidcProxy.volumeMounts| nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- with (mergeOverwrite 
              (dict)
              (.Values.annotations)
              (.Values.oidcProxy.annotations)
        ) }}
        {{- toYaml . | nindent 4 }}
        {{- end }}
  labels:
    {{- include "oidcProxy.labels" . | nindent 4 }}
  name: {{ include "oidcProxy.name" . }}
spec:
  ports:
    - name: http
      port: {{ include "oidcProxy.port" . }}
      protocol: TCP
      targetPort: {{ include "oidcProxy.port" . }}
  selector:
    {{- include "oidcProxy.selectorLabels" . | nindent 4 }}

---
{{- end -}}
{{- end -}}
