{{ $global := . }}
{{- $kind := default "Deployment" .Values.global.deploymentKind }}
{{- if eq $kind "Rollout" }}
{{- range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $service }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    {{- $rolloutAnnotations := default dict (get (default dict $global.Values.global.rollout) "annotations") }}

    {{- toYaml (mergeOverwrite
                (dict)
                (fromYaml (include "stack.annotations" $service ))
                (default dict $rolloutAnnotations) 
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.args (ne (len .Values.args) 0) }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if and .Values.command (ne (len .Values.command) 0) }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- include "container.probe" .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- include "container.probe" .Values.readinessProbe | nindent 12 }}
          {{- if eq .Values.startupProbe.enabled true }}
          startupProbe:
            {{- include "container.probe" (omit .Values.startupProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (and .Values.persistence.enabled .Values.persistence.mountPath) .Values.volumeMounts}}
          volumeMounts:
            {{- if and .Values.persistence.enabled .Values.persistence.mountPath }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- include "service.configuration" . | nindent 10}}
          {{- include "service.nonsensitiveEnvVars" (list $global.Values.global .Values) | nindent 10 }}
        {{- if .Values.sidecars }}
        {{- range $i, $container := .Values.sidecars }}
        {{- $imageDict := fromYaml (include "image" $container) }}
        {{- $container = mergeOverwrite $container $imageDict }}
        {{- with omit $container "envFrom" "env" }}
        - {{- toYaml . | nindent 10 }}
          {{- include "service.configuration" $service | nindent 10}}
        {{- end }}
        {{- include "service.nonsensitiveEnvVars" (list $global.Values.global $service.Values $container) | nindent 10 }}
        {{- end }}
        {{- end }}
      {{if .Values.initContainers }}
      initContainers:
      {{- range $i, $container := .Values.initContainers }}
      {{- $imageDict := fromYaml (include "image" $container) }}
      {{- $container = mergeOverwrite $container $imageDict }}
      {{- with omit $container "envFrom" "env" }}
        - {{- toYaml . | nindent 10 }}
          {{- include "service.configuration" $service | nindent 10}}
      {{- end }}
      {{- include "service.nonsensitiveEnvVars" (list $global.Values.global $service.Values $container) | nindent 10 }}
      {{- end }}
      {{end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- if or .Values.persistence.enabled .Values.volumes}}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "service.claimName" . }}
        {{- end }}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "service.selectorLabels" . | nindent 14 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    {{- $rolloutStrategy := default dict (get (default dict $global.Values.global) "rollout") }}
    {{- $rolloutStrategy = default dict (get $rolloutStrategy "strategy") }}
    {{- $blueGreenStrategy := default dict (get $rolloutStrategy "blueGreen") }}
    blueGreen:
      activeService: {{ default (printf "%s-service" (include "service.fullname" .)) $blueGreenStrategy.activeService }}
      previewService: {{ default (printf "%s-previewService" (include "service.fullname" .)) $blueGreenStrategy.previewService }}
      autoPromotionEnabled: {{ default false $blueGreenStrategy.autoPromotionEnabled }}
      {{- with $blueGreenStrategy.postInboundTraffic }}
      postInboundTraffic:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $blueGreenStrategy.prePromotionAnalysis }}
      prePromotionAnalysis:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
