{{- if .Values.global.s3Storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.s3Storage.pvcName | default (printf "%s-s3-pvc" (include "stack.fullname" .)) }}
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    {{- with .Values.global.s3Storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.s3Storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.global.s3Storage.accessModes | nindent 4 }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.global.s3Storage.capacity | default "5Gi" }}
  volumeName: {{ .Values.global.s3Storage.pvName | default (printf "%s-s3-pv" (include "stack.fullname" .)) }}
{{- end }}
