{{ $global := . }}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $service }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    {{- include "stack.annotations" $service | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.ports }}
  {{- range .Values.service.ports }}
    - name: {{ .name | default "http" }}
      port: {{ .containerPort }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .name | default "http" }}
  {{- end }}
  {{- else }}
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .name | default "http" }}
  {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
---
{{- end }}
{{- end }}