{{ $global := . }}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities -}}
  {{- $values := mergeOverwrite $global.Values.global $serviceValues -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $service = set $service "Values" $values -}}
{{- with $service -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with merge .Values.serviceAccount.annotations .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
{{- end }}
{{- end }}