{{ $global := . }}
{{ range $serviceName, $serviceValues := .Values.services }}
  {{- $globalValuesDict := $global.Values.global | toYaml -}}
  {{- $values := fromYaml $globalValuesDict -}}
  {{- $values = set $values "name" $serviceName -}}
  {{- $values := mergeOverwrite $values $serviceValues -}}
  {{- $service := dict "Chart" $global.Chart "Release" $global.Release "Capabilities" $global.Capabilities "Values" $values -}}
{{- with $service }}

{{- if eq .Values.workload.type "statefulset" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-headless
  labels:
    {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless-service
  annotations:
    {{- include "stack.annotations" $service | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None  # This makes it a headless service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- end }}
{{- end }}
