apiVersion: v2
name: grafana-alloy
description: A Helm chart for deploying Grafana Alloy with custom configuration
type: application
version: 0.1.0

dependencies:
  - name: alloy
    version: 1.5.1
    repository: https://grafana.github.io/helm-charts
    condition: enabled

