{
 "title": "{{ .Values.loki.dashboardTitle }}",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful API Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status_code, route) (rate(loki_request_duration_seconds_count{namespace=\"{{ .Values.loki.namespace }}\", method!=\"gRPC\", status_code=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed API Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status_code, route) (rate(loki_request_duration_seconds_count{namespace=\"{{ .Values.loki.namespace }}\", method!=\"gRPC\", status_code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{namespace=\"{{ .Values.loki.namespace }}\"}[5m])) by (le,route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable deployment pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_unavailable{namespace=\"{{ .Values.loki.namespace }}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable stateful set pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(statefulset) (kube_statefulset_status_replicas_ready{namespace=\"{{ .Values.loki.namespace }}\"}) - (sum by(statefulset) (kube_statefulset_status_replicas{namespace=\"{{ .Values.loki.namespace }}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{namespace=\"{{ .Values.loki.namespace }}\"}[5m])) by (le,type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LogQL Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{namespace=\"{{ .Values.loki.namespace }}\"}[5m])) by (le,type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  }
 ]
}