{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
  labels:
    {{- include "karpenter-gpu-nodepool.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value }}
globalDefault: {{ .Values.priorityClass.globalDefault }}
preemptionPolicy: {{ .Values.priorityClass.preemptionPolicy }}
description: {{ .Values.priorityClass.description | quote }}
{{- end }}

