{{ $global := . }}
{{- with $global.Values.global }}
{{ range $secretsKey, $secretValue := .appSecrets }}
{{- if ne (trim $secretValue.secretName) "" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretValue.secretName }}
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: "10m"
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - target: Data
          literal: "{{ `{{ range $key, $value := . }}\n{{ range $name, $val := $value | fromJson }}\n{{$name | upper}}: {{$val}}\n{{ end }}\n{{ end }}\n` }}"
  data:
    # test specifying 2 data blocks to see if overriding works
    - secretKey: {{ $secretValue.secretName }}
      remoteRef:
        key: {{ $secretValue.secretKey }}
        conversionStrategy: Default
        decodingStrategy: None
{{end}}
{{end}}
{{end}}
