{{ $global := . }}
{{- with $global.Values.global }}

# omit the clusterSecret and clusterCLISecret because they are created automatically
# by the ClusterExternalSecret in argus-infra-stacks.
{{ range $secretsKey, $secretValue := (omit .appSecrets "clusterSecret" "clusterCLISecret") }}
{{- if ne (trim $secretValue.secretName) "" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretValue.secretName }}
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: "10m"
  target:
    deletionPolicy: Delete
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $secretValue.secretKey }}
{{end}}
{{end}}
{{end}}
