{
 "title": "Kubernetes Cluster Health",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes by Condition",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(count by(node) (kube_node_status_condition{condition=\"Ready\"} == 1)) or vector(0)",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "count(count by(node) (kube_node_status_condition{condition=\"Ready\", status=\"true\"} == 1)) or vector(0)",
     "legendFormat": "Ready Nodes"
    },
    {
     "expr": "count(count by(node) (kube_node_status_condition{condition=\"Ready\", status=\"false\"} == 1)) or vector(0)",
     "legendFormat": "NotReady Nodes"
    }
   ]
  },
  {
   "title": "Pods In Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count(count by(pod) (kube_pod_status_phase{} == 1)) or vector(0)",
     "legendFormat": "Total Pods"
    },
    {
     "expr": "count(count by(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "count(count by(pod) (kube_pod_status_phase{phase=\"Pending\"} == 1))",
     "legendFormat": "Pending Pods"
    },
    {
     "expr": "count(count by(pod) (kube_pod_status_phase{phase=\"Failed\"} == 1))",
     "legendFormat": "Failed Pods"
    },
    {
     "expr": "count(count by(pod) (kube_pod_status_phase{phase=\"Succeeded\"} == 1))",
     "legendFormat": "Succeeded Pods"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"}) or vector(0)",
     "legendFormat": "Available CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Total Requested CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"}) or vector(0)",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Total Requested Memory"
    }
   ]
  },
  { "title": "Resource Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Pressure (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"} * on(pod, namespace) group_left max by(pod,namespace) (kube_pod_status_phase{phase=\"Running\"})) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})) * 100 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"} * on(pod, namespace) group_left max by(pod,namespace) (kube_pod_status_phase{phase=\"Running\"})) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})) * 100 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Unsatisfied Resource Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Unbound PVCs in Cluster (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(count(count by(persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"} == 1))) / (count(count by(persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{} == 1))) * 100 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods in Cluster by Phase (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(count(count by(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) / count(count by(pod) (kube_pod_status_phase{} == 1))) * 100 or vector(0)",
     "legendFormat": "% of Running pods"
    },
    {
     "expr": "(count(count by(pod) (kube_pod_status_phase{phase=\"Pending\"} == 1)) / count(count by(pod) (kube_pod_status_phase{} == 1))) * 100 or vector(0)",
     "legendFormat": "% of Pending pods"
    },
    {
     "expr": "(count(count by(pod) (kube_pod_status_phase{phase=\"Failed\"} == 1)) / count(count by(pod) (kube_pod_status_phase{} == 1))) * 100 or vector(0)",
     "legendFormat": "% of Failed pods"
    },
    {
     "expr": "(count(count by(pod) (kube_pod_status_phase{phase=\"Succeeded\"} == 1)) / count(count by(pod) (kube_pod_status_phase{} == 1))) * 100 or vector(0)",
     "legendFormat": "% of Succeeded pods"
    },
    {
     "expr": "(count(count by(pod) (kube_pod_status_phase{phase=\"Unknown\"} == 1)) / count(count by(pod) (kube_pod_status_phase{} == 1))) * 100 or vector(0)",
     "legendFormat": "% of Unknown pods"
    }
   ]
  },
  {
   "title": "Expired or Unissued Certificates (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "(count(count by(name) (certmanager_certificate_ready_status{condition!=\"True\"} == 1)) / count(count by(name) (certmanager_certificate_ready_status{} == 1)) ) * 100 or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(count(count by(name) (certmanager_certificate_expiration_timestamp_seconds{} - time() < 604800)) / count(count by(name) (certmanager_certificate_ready_status{} == 1)) ) * 100 or vector(0)",
     "legendFormat": "Expiring in the next 7 days"
    }
   ]
  }
 ]
}