# @schema type: object
# @schema description: defines a template that is used to create a analysisRun
# @schema additionalProperties: true
rolloutAnalysis:
  # @schema item: object
  # @schema itemProperties: {"templateName": {"type": "string", "description": " name of the AnalysisTemplate to use for the rollout analysis"}, "clusterScope": {"type": "boolean", "description": "Whether to look for the templateName at cluster scope or namespace scope."}}
  # @schema description: reference to a list of analysis templates to combine for an AnalysisRun
  templates: []
  # @schema item: object
  # @schema itemProperties: {"name": {"type": "string"}, "value": {"type": "string"}, "valueFrom": {"type": "object", properties: {"podTemplateHashValue": {"type": "string", "enum": ["Latest", "Stable"]}, "fieldRef": {"type":"object", "properties": {"fieldPath": {"type": "string"}}}}}}
  # @schema description: the arguments that will be added to the AnalysisRuns
  args: []
  # @schema type: object
  # @schema description: extra labels to add to the AnalysisRun
  analysisRunMetadata:
    # @schema type: object
    # @schema description: additional labels to add to the AnalysisRun
    labels: {}
    # @schema type: object
    # @schema description: additional annotations to add to the AnalysisRun
    annotations: {}
# @schema patternProperties: { "^.*$": {"$ref": "#/properties/global", "type": "object", "unevaluatedProperties": false } }; description: Services to deploy
services: {}
# @schema additionalProperties: true
# @schema description: Global parameters
global:
  # @schema description: Specifies the rollout strategy for the application.
  # @schema type: object
  # @schema default: bluegreen
  strategy:
    # @schema additionalProperties: true
    bluegreen:
      # @schema type: string
      # @schema description: Name of the service that the rollout modifies as the active service.
      activeService: ""
      # @schema type: string
      # @schema description: Name of the service that the rollout modifies as the preview service.
      previewService: ""
      # @schema type: boolean
      # @schema description: indicates if the rollout should automatically promote the new ReplicaSet to the active service or enter a paused state.
      autoPromotionEnabled: false
      # @schema $ref: #/properties/rolloutAnalysis
      # @schema description: configuration to run analysis before a selector switch
      prePromotionAnalysis: {}
  
  