## @section Global parameters

## @param clusterName Name of the cluster to configure the platform Grafana for. This value is required.
clusterName: ""

## @param baseDomain Base domain for cluster ingresses (e.g. dev-core-platform.dev.czi.team). This value is required.
baseDomain: ""

## @param grafanaName Name of the Grafana instance to create.
grafanaName: "grafana"

## @param replicas Number of Grafana replicas to create. When greater than 1, database persistence is required (not supported yet).
replicas: 1

## @param secretStoreRef Name of the secret store to use for external secrets.
secretStoreRef: "aws-secretsmanager"

## @param roleAttributePath JMESPath expression to use to determine the role of the user. See https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/ .
roleAttributePath: "contains(groups[*], 'team-central-czi-admin') && 'Admin' || contains(groups[*], 'team-pep-dev-core-platform-argus-obs.Admin') && 'Admin' || 'Viewer'"

## @param grafanaAnnotations Annotations to add to the Grafana instance.
grafanaAnnotations: {}

## @param grafanaSubdomain Subdomain to use for the Grafana instance.
grafanaSubdomain: "grafana"

## @param datasources List of datasources to configure for the Grafana instance.
datasources:
  ## @param loki Loki datasource configuration.
  loki:
    ## @param enabled Enable the Loki datasource.
    enabled: true
    ## @param url URL of the Loki datasource.
    url: "http://loki.loki.svc:3100/"
  ## @param prometheus Prometheus datasource configuration.
  prometheus:
    ## @param enabled Enable the Prometheus datasource.
    enabled: true
    ## @param url URL of the Prometheus datasource.
    url: "http://loki-stack-prometheus-server"
  ## @param tempo Tempo datasource configuration.
  tempo:
    ## @param enabled Enable the Tempo datasource.
    enabled: true
    ## @param url URL of the Tempo datasource.
    url: "http://tempo.loki.svc:3100"