enabled: true # @schema description: Enable the Grafana instance.

grafanaBaseImage: "docker.io/grafana/grafana:11.3.0" # @schema description: Base image for the Grafana instance.

clusterName: "" # @schema description: Name of the cluster to configure the platform Grafana for. This value is required.; required: true

baseDomain: "" ## @schema description: Base domain for cluster ingresses (e.g. dev-core-platform.dev.czi.team). This value is required.; required: true

grafanaName: "grafana" # @schema description: Name of the Grafana instance to create.

replicas: 1 # @schema description: Number of Grafana replicas to create. When greater than 1, database persistence is required (not supported yet), as well as session affinity.; maximum: 1 

secretStoreRef: "aws-secretsmanager" # @schema description: Name of the secret store to use for external secrets.

roleAttributePath: "contains(groups[*], 'team-central-czi-admin') && 'Admin' || 'Viewer'" # @schema description: JMESPath expression to use to determine the role of the user. See https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/ .

grafanaAnnotations: {} # @schema description: Annotations to add to the Grafana instance.; patternProperties: { "^.*$": { "type": "string" } }

grafanaSubdomain: "grafana" # @schema description: Subdomain to use for the Grafana instance.

env: {} # @schema description: Environment variables to set in the Grafana instance. This can be used to set custom environment variables for Grafana.; patternProperties: { "^.*$": { "type": "string" } }

datasources: # @schema description: List of datasources to configure for the Grafana instance.
  loki: # @schema description: Loki datasource configuration.
    enabled: true # @schema description: Enable the Loki datasource.
    url: "http://loki.loki.svc:3100/" # @schema description: URL of the Loki datasource.
  prometheus: # @schema description: Prometheus datasource configuration.
    enabled: true # @schema description: Enable the Prometheus datasource.
    url: "http://loki-stack-prometheus-server.loki.svc" # @schema description: URL of the Prometheus datasource.
  tempo: # @schema description: Tempo datasource configuration.
    enabled: true # @schema description: Enable the Tempo datasource.
    url: "http://tempo.loki.svc:3100" # @schema description: URL of the Tempo datasource.
  aps: # @schema description: Amazon Managed Prometheus datasource configuration.
    enabled: true # @schema description: Enable the Amazon Managed Prometheus datasource.
    url: "" # @schema description: URL of the Amazon Managed Prometheus datasource.

extraSecretVolumes: [] # @schema description: List of extra secret volumes to mount in the Grafana instance. Each entry should be a map with the following keys:
  # - name: slack-webhook-secret
  #   secret:
  #     secretName: slack-webhook-secret
  #     defaultMode: 0444

  #   OR

  # - name: <name>
  #   configMap:
  #     configMapName: <some-name>
  #     defaultMode: 0444

serviceAccount:
  annotations: {} # @schema description: Annotations to add to the service account.; patternProperties: { "^.*$": { "type": "string" } }