{{- if or .Values.proxyProtocol.enabled .Values.hsts.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: {{ .Values.gatewayName }}-client-traffic
  namespace: envoy-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewayName }}
  {{- if .Values.proxyProtocol.enabled }}
  proxyProtocol:
    optional: {{ .Values.proxyProtocol.optional }}
  {{- end }}
  {{- if .Values.hsts.enabled }}
  headers:
    lateResponseHeaders:
      addIfAbsent:
        - name: Strict-Transport-Security
          value: {{ .Values.hsts.value | quote }}
  {{- end }}
{{- end }}
