{{- if .Values.geoip.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: maxmind-license
  namespace: envoy-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: maxmind-license
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cluster-secret
{{- end }}
