{{- if and .Values.geoip.enabled .Values.geoip.s3.iamRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gatewayName }}-envoy
  namespace: envoy-gateway
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.geoip.s3.iamRoleArn | quote }}
{{- end }}
