projectName: my-cluster-addons
namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "cw-loki"
      server: "*"
  sourceRepos:
    - "*"
