{{- range $kind := list "runtime" "migration" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ops-telemetry-{{ $kind }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: ops-telemetry-{{ $kind }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $.Values.secretPrefix }}/{{ $kind }}
{{- end }}
