apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BASIC_AUTH_CREDENTIALS: '{{ include "escape" "printf \"%s:%s\" .USERNAME .PASSWORD | b64enc" }}'
  data:
  - secretKey: USERNAME
    remoteRef:
      key: "{{ .Values.keyPrefix }}/basic-auth-secret/user_name"
  - secretKey: PASSWORD
    remoteRef:
      key: "{{ .Values.keyPrefix }}/basic-auth-secret/password"
