apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: {{ .Values.clusterName }}/{{ .Values.applicationName }}/oauth/client-id
  - secretKey: client-secret
    remoteRef:
      key: {{ .Values.clusterName }}/{{ .Values.applicationName }}/oauth/client-secret