clusterRole:
  name: czi-argo-workflows-server-cluster-template # @schema description: Cluster Role name to create
  rules:
  - apiGroups: # @schema description: API groups to apply the rules to
    - argoproj.io
    resources: # @schema description: Resources to apply the rules to
    - clusterworkflowtemplates
    verbs: # @schema description: Verbs to apply the rules to
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete