{{ if .Values.eventsources.webhook }}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      {{- range $webhookName, $webhookValue := .Values.eventsources.webhook }}
      - port: {{ $webhookValue.port | default "12000" }}
        targetPort: {{ $webhookValue.port | default "12000" }}
     {{- end }}
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    {{- range $webhookName, $webhookValue := .Values.eventsources.webhook }}
      {{ $webhookName }}:
        port: {{ $webhookValue.port | default "12000" }}
        endpoint: {{ $webhookValue.endpoint | default "/example" }}
        method: {{ $webhookValue.method | default "POST" }}
     {{- end }}
{{- end }}