global:
  deploymentKind: Rollout
services:
  service1:
    rollout:
      strategy:
        blueGreen:
          autoPromotionEnabled: false
          prePromotionAnalysis:
            templates:
              - templateName: example-prepromo-analysis-template
            analysisRunMetadata:
              annotations:
                test: "value"
    args: ["arg1", "arg2"]
    command: ["command1", "command2"]
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      maxUnavailable: 1
    replicaCount: 2
    sidecars:
      - name: sidecar1
        image: "sidecar1:latest"
      - name: sidecar2
        image: "sidecar2:latest"
    initContainers:
      - name: initContainer1
        image: "alpine:latest"
        command: ["echo", "Hello World"]
  service2:
    rollout:
      strategy:
        blueGreen:
          autoPromotionEnabled: false
          prePromotionAnalysis:
            templates:
              - templateName: example-prepromo-analysis-template
            analysisRunMetadata:
              annotations:
                test: "value"
    args: ["arg1", "arg2"]
    command: ["command1", "command2"]
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      maxUnavailable: 1
    replicaCount: 2
    initContainers:
      - name: initContainer1
        image: "alpine:latest"
        command: ["echo", "Hello World"]