## @section Global parameters

## @param clusterName Name of the cluster to configure the sso secret for
clusterName: my-cluster

## @param secretName Name of the secret to create (both external secret and kubernetes secret resources)
secretName: my-sso-secret

## @param applicationName Name of the application to configure the sso secret for
applicationName: my-app