{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cluster-healthcheck.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-healthcheck.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "cluster-healthcheck.selectorLabels" . | nindent 6 }}
{{- end }}

