{{ if .Values.enabled }}
{{ if .Values.alertRuleGroup.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: {{.Values.alertRuleGroup.name}}
spec:
  folderRef: {{.Values.folder.name}}
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      app: {{.Values.grafana.name}}
  interval: 5m
  name: {{.Values.alertRuleGroup.title}}
  rules:
  - uid: aev0cykoq1m2od
    title: Loki Error Spike
    condition: C
    data:
      - refId: A
        relativeTimeRange:
          from: 600
          to: 0
        datasourceUid: prometheus
        model:
          datasource:
              type: prometheus
              uid: prometheus
          editorMode: code
          expr: |-
              sum(
                increase(loki_request_duration_seconds_count{
                  namespace="{{ .Values.loki.namespace }}",
                  status_code=~"5..",
                  method!="gRPC"
                }[5m])
              )
          hide: false
          instant: true
          intervalMs: 1000
          legendFormat: __auto
          maxDataPoints: 43200
          range: false
          refId: A
      - refId: C
        datasourceUid: __expr__
        model:
          conditions:
              - evaluator:
                  params:
                      - 0
                  type: gt
                operator:
                  type: and
                query:
                  params:
                      - C
                reducer:
                  params: []
                  type: last
                type: query
          datasource:
              type: __expr__
              uid: __expr__
          expression: A
          intervalMs: 1000
          maxDataPoints: 43200
          refId: C
          type: threshold
    noDataState: OK
    execErrState: OK
    for: 5m
    isPaused: false
  - uid: cev0decuulh4wd
    title: Loki LogQL Latency Spike
    condition: C
    data:
      - refId: A
        relativeTimeRange:
          from: 600
          to: 0
        datasourceUid: prometheus
        model:
          datasource:
              type: prometheus
              uid: prometheus
          disableTextWrap: false
          editorMode: builder
          expr: histogram_quantile(0.95, sum by(le, type) (rate(loki_logql_querystats_latency_seconds_bucket{namespace="{{ .Values.loki.namespace }}", type="metric"}[5m])))
          fullMetaSearch: false
          includeNullMetadata: true
          instant: true
          intervalMs: 1000
          legendFormat: __auto
          maxDataPoints: 43200
          range: false
          refId: A
          useBackend: false
      - refId: C
        datasourceUid: __expr__
        model:
          conditions:
              - evaluator:
                  params:
                      - 1
                  type: gt
                operator:
                  type: and
                query:
                  params:
                      - C
                reducer:
                  params: []
                  type: last
                type: query
          datasource:
              type: __expr__
              uid: __expr__
          expression: A
          intervalMs: 1000
          maxDataPoints: 43200
          refId: C
          type: threshold
    noDataState: OK
    execErrState: OK
    annotations: {}
    labels: {}
    isPaused: false
  - uid: cev3mcuwlz6dcc
    title: Statefulset pods unavailable
    condition: C
    data:
      - refId: A
        relativeTimeRange:
          from: 600
          to: 0
        datasourceUid: prometheus
        model:
          datasource:
              type: prometheus
              uid: prometheus
          editorMode: code
          expr: sum by(statefulset) (kube_statefulset_status_replicas_ready{namespace="{{ .Values.loki.namespace }}"}) - (sum by(statefulset) (kube_statefulset_status_replicas{namespace="{{ .Values.loki.namespace }}"}))
          instant: true
          intervalMs: 1000
          legendFormat: __auto
          maxDataPoints: 43200
          range: false
          refId: A
      - refId: C
        datasourceUid: __expr__
        model:
          conditions:
              - evaluator:
                  params:
                      - 0
                  type: gt
                operator:
                  type: and
                query:
                  params:
                      - C
                reducer:
                  params: []
                  type: last
                type: query
          datasource:
              type: __expr__
              uid: __expr__
          expression: A
          intervalMs: 1000
          maxDataPoints: 43200
          refId: C
          type: threshold
    noDataState: OK
    execErrState: OK
    annotations: {}
    labels: {}
    isPaused: false
  - uid: bev3mo5h2ihogf
    title: Deployment pods unavailable
    condition: C
    data:
      - refId: A
        relativeTimeRange:
          from: 600
          to: 0
        datasourceUid: prometheus
        model:
          datasource:
              type: prometheus
              uid: prometheus
          editorMode: code
          expr: sum by(deployment) (kube_deployment_status_replicas_unavailable{namespace="{{ .Values.loki.namespace }}"})
          instant: true
          intervalMs: 1000
          legendFormat: __auto
          maxDataPoints: 43200
          range: false
          refId: A
      - refId: C
        datasourceUid: __expr__
        model:
          conditions:
              - evaluator:
                  params:
                      - 0
                  type: gt
                operator:
                  type: and
                query:
                  params:
                      - C
                reducer:
                  params: []
                  type: last
                type: query
          datasource:
              type: __expr__
              uid: __expr__
          expression: A
          intervalMs: 1000
          maxDataPoints: 43200
          refId: C
          type: threshold
    noDataState: OK
    execErrState: OK
    for: 5m
    annotations: {}
    labels: {}
    isPaused: false
    notification_settings:
      receiver: grafana-default-email
{{ end }}
{{ end }}