clusterName: ""

nodepool:
  enabled: true
  name: default
  annotations: {}
  weight: null
  limits: {}

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 24h
    budgets: []

  template:
    metadata:
      labels: {}
      annotations: {}

    spec:
      terminationGracePeriod: 1h
      expireAfter: 360h

      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      startupTaints: []
      taints: []

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - nano
            - micro
            - small
        - key: karpenter.k8s.aws/instance-cpu
          operator: Gt
          values:
            - "8"
        - key: karpenter.k8s.aws/instance-family
          operator: NotIn
          values:
            - a1
            - c1
            - cc1
            - cc2
            - cg1
            - cg2
            - cr1
            - g1
            - g2
            - hi1
            - hs1
            - m1
            - m2
            - m3
            - t1

nodeclass:
  enabled: true
  name: default
  annotations: {}
  role: ""
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  kubelet:
    systemReserved:
      cpu: 100m
      memory: 100Mi
    podsPerCore: 14

  volumeSizeGi: 100
  tags: {}
